entity_configs:
  Branch:
    aliases: &id001
      priority: 3
      strategy: append_unique
      target_field: aliases
    createdBy:
      priority: 2
      strategy: preserve_existing
      target_field: createdBy
    description: &id002
      priority: 3
      strategy: append_unique
      target_field: rawDescriptions
      transform: append_to_array
    name: &id003
      priority: 2
      strategy: preserve_existing
      target_field: name
    repo:
      priority: 1
      strategy: preserve_existing
      target_field: repo
    sources: &id004
      priority: 3
      strategy: append_unique
      target_field: sources
  CodeChangeRequest:
    aliases: *id001
    author:
      priority: 2
      strategy: preserve_existing
      target_field: author
    createdAt:
      priority: 2
      strategy: preserve_existing
      target_field: createdAt
      transform: parse_timestamp
    description: *id002
    id:
      priority: 1
      strategy: preserve_existing
      target_field: id
    name: *id003
    reviewers:
      priority: 3
      strategy: append_unique
      target_field: reviewers
    sources: *id004
    status:
      priority: 4
      strategy: replace_always
      target_field: status
    title:
      priority: 2
      strategy: preserve_existing
      target_field: title
  Event:
    aliases: *id001
    description: *id002
    name: *id003
    sources: *id004
    startTime:
      priority: 2
      strategy: preserve_existing
      target_field: startTime
      transform: parse_timestamp
    type:
      priority: 2
      strategy: preserve_existing
      target_field: type
  Issue:
    aliases: *id001
    description: *id002
    id:
      priority: 1
      strategy: preserve_existing
      target_field: id
    labels:
      priority: 3
      strategy: append_unique
      target_field: labels
    name: *id003
    sources: *id004
    status:
      priority: 4
      strategy: replace_always
      target_field: status
    title:
      priority: 2
      strategy: preserve_existing
      target_field: name
  Organization:
    aliases: *id001
    description: *id002
    domain:
      priority: 1
      strategy: preserve_existing
      target_field: domain
    industry:
      priority: 3
      strategy: replace_if_better
      target_field: industry
    location:
      priority: 3
      strategy: append_unique
      target_field: location
    name: *id003
    sources: *id004
  Person:
    aliases: *id001
    cleanDescription:
      priority: 5
      strategy: agent_only
      target_field: cleanDescription
    description: *id002
    email:
      priority: 1
      strategy: preserve_existing
      target_field: email
    name: *id003
    role:
      priority: 3
      strategy: append_unique
      target_field: role
    sources: *id004
  Project:
    aliases: *id001
    description: *id002
    name: *id003
    sources: *id004
    status:
      priority: 4
      strategy: replace_always
      target_field: status
    tags:
      priority: 3
      strategy: append_unique
      target_field: tags
  Repository:
    aliases: *id001
    description: *id002
    language:
      priority: 3
      strategy: replace_if_better
      target_field: language
    name: *id003
    sources: *id004
    url:
      priority: 1
      strategy: preserve_existing
      target_field: url
  Team:
    aliases: *id001
    description: *id002
    name: *id003
    sources: *id004
  Topic:
    aliases: *id001
    description: *id002
    keywords:
      priority: 3
      strategy: append_unique
      target_field: keywords
    name: *id003
    relatedThreads:
      priority: 3
      strategy: append_unique
      target_field: relatedThreads
    sources: *id004
field_mappings:
  agent_only:
  - cleanDescription
  always_preserve:
  - entity_id
  - lastUpdated
  - createdAt
  - embedding
  array_fields:
  - rawDescriptions
  - sources
  - aliases
  - role
  - location
  - tags
  - reviewers
  - assignees
  - labels
  - keywords
  - relatedThreads
  critical_fields:
  - entity_id
  - email
  - domain
  - url
  timestamp_fields:
  - createdAt
  - mergedAt
  - closedAt
  - startTime
