# ==================== PEOPLE & ORGANIZATION ====================
Person:
  entity_id: STRING PRIMARY KEY
  name: STRING
  email: STRING
  role: STRING[]
  aliases: STRING[]
  sourceSystemId: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  sources: STRING[]              # list of doc/mail/thread IDs
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Team:
  entity_id: STRING PRIMARY KEY
  name: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Organization:
  entity_id: STRING PRIMARY KEY
  name: STRING
  domain: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  industry: STRING
  location: STRING[]
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

# ==================== PROJECTS & WORK ====================
Project:
  entity_id: STRING PRIMARY KEY
  name: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  status: STRING
  startDate: DATE
  endDate: DATE
  client: STRING
  tags: STRING[]
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

# ==================== CODE & DEVELOPMENT ====================
Repository:
  entity_id: STRING PRIMARY KEY
  name: STRING
  url: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  language: STRING
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Branch:
  entity_id: STRING PRIMARY KEY
  name: STRING
  repo: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  createdBy: STRING
  createdAt: TIMESTAMP
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

CodeChangeRequest:   # PullRequest / MergeRequest / CodeReview combined
  entity_id: STRING PRIMARY KEY
  title: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  status: STRING
  author: STRING
  reviewers: STRING[]             # list of Person.entity_id
  repo: STRING
  branch: STRING
  createdAt: TIMESTAMP
  mergedAt: TIMESTAMP
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Issue:
  entity_id: STRING PRIMARY KEY
  title: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  status: STRING
  reporter: STRING
  assignees: STRING[]
  labels: STRING[]
  createdAt: TIMESTAMP
  closedAt: TIMESTAMP
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Event:
  entity_id: STRING PRIMARY KEY
  title: STRING
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  type: STRING
  startTime: TIMESTAMP
  linkedProject: STRING
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

Topic:
  entity_id: STRING PRIMARY KEY
  name: STRING
  keywords: STRING[]
  relatedThreads: STRING[]
  rawDescriptions: STRING[]      # direct extracted text from docs/mails
  cleanDescription: STRING       # cleaned/normalized description
  sources: STRING[]
  lastUpdated: TIMESTAMP
  embedding: DOUBLE[]

# ==================== RELATIONSHIPS ====================
Relation:
  relation_id: STRING PRIMARY KEY
  from_entity: STRING
  description: STRING
  relationTag: STRING
  to_entity: STRING
  type: STRING
  strength: FLOAT
  source: STRING
  createdAt: TIMESTAMP
